/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"github.com/gin-gonic/gin"
)

type LocationsAPI interface {


    // CreateLocation Post /v1/locations
    // Create location 
     CreateLocation(c *gin.Context)

    // DeleteLocation Delete /v1/locations/:locationId
    // Delete location 
     DeleteLocation(c *gin.Context)

    // GetLocation Get /v1/locations/:locationId
    // Get location 
     GetLocation(c *gin.Context)

    // ListEquipmentAtLocation Get /v1/locations/:locationId/equipment
    // List equipment at a location 
     ListEquipmentAtLocation(c *gin.Context)

    // ListLocations Get /v1/locations
    // List locations 
     ListLocations(c *gin.Context)

    // UpdateLocation Put /v1/locations/:locationId
    // Update location 
     UpdateLocation(c *gin.Context)

}