/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"github.com/gin-gonic/gin"
)

type EquipmentAPI interface {


    // CreateEquipment Post /equipment
    // Create equipment 
     CreateEquipment(c *gin.Context)

    // DecommissionEquipment Delete /equipment/:equipmentId
    // Decommission equipment 
     DecommissionEquipment(c *gin.Context)

    // GetEquipment Get /equipment/:equipmentId
    // Get equipment 
     GetEquipment(c *gin.Context)

    // ListEquipment Get /equipment
    // List equipment 
     ListEquipment(c *gin.Context)

    // UpdateEquipment Put /equipment/:equipmentId
    // Update equipment 
     UpdateEquipment(c *gin.Context)

}