/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"github.com/gin-gonic/gin"
)

type ServiceRequestsAPI interface {


    // CreateServiceRequest Post /v1/service-requests
    // Create service request 
     CreateServiceRequest(c *gin.Context)

    // DeleteServiceRequest Delete /v1/service-requests/:requestId
    // Delete service request 
     DeleteServiceRequest(c *gin.Context)

    // GetServiceRequest Get /v1/service-requests/:requestId
    // Get service request 
     GetServiceRequest(c *gin.Context)

    // ListServiceRequests Get /v1/service-requests
    // List service requests 
     ListServiceRequests(c *gin.Context)

    // TransitionServiceRequestStatus Patch /v1/service-requests/:requestId/status
    // Transition service request status 
     TransitionServiceRequestStatus(c *gin.Context)

    // UpdateServiceRequest Put /v1/service-requests/:requestId
    // Update service request details 
     UpdateServiceRequest(c *gin.Context)

}