/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"github.com/gin-gonic/gin"
)

type EquipmentAPI interface {


    // CreateEquipment Post /v1/equipment
    // Create equipment 
     CreateEquipment(c *gin.Context)

    // DecommissionEquipment Delete /v1/equipment/:equipmentId
    // Decommission equipment 
     DecommissionEquipment(c *gin.Context)

    // GetEquipment Get /v1/equipment/:equipmentId
    // Get equipment 
     GetEquipment(c *gin.Context)

    // ListEquipment Get /v1/equipment
    // List equipment 
     ListEquipment(c *gin.Context)

    // ListEquipmentAtLocation Get /v1/locations/:locationId/equipment
    // List equipment at a location 
     ListEquipmentAtLocation(c *gin.Context)

    // ListEquipmentServiceRequests Get /v1/equipment/:equipmentId/service-requests
    // List service requests for equipment 
     ListEquipmentServiceRequests(c *gin.Context)

    // MoveEquipment Patch /v1/equipment/:equipmentId/location
    // Move equipment to a new location 
     MoveEquipment(c *gin.Context)

    // UpdateEquipment Put /v1/equipment/:equipmentId
    // Update equipment 
     UpdateEquipment(c *gin.Context)

}