/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"time"
)

type Location struct {

	Building string `json:"building"`

	Floor string `json:"floor"`

	Department string `json:"department"`

	Room string `json:"room"`

	Description string `json:"description,omitempty"`

	Id string `json:"id"`

	// Number of active equipment items currently at this location
	EquipmentCount int32 `json:"equipmentCount,omitempty"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`
}
