/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type ErrorDetailsInner struct {

	Field string `json:"field,omitempty"`

	Message string `json:"message,omitempty"`
}
