/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi
// ServiceRequestStatus : - `NEW` – submitted, awaiting assignment - `ASSIGNED` – assigned to a technician - `IN_PROGRESS` – technician is actively working on it - `CLOSED` – resolved and closed 
type ServiceRequestStatus string

// List of ServiceRequestStatus
const (
	NEW ServiceRequestStatus = "NEW"
	ASSIGNED ServiceRequestStatus = "ASSIGNED"
	IN_PROGRESS ServiceRequestStatus = "IN_PROGRESS"
	CLOSED ServiceRequestStatus = "CLOSED"
)
