/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type Priority string

// List of Priority
const (
	LOW Priority = "LOW"
	MEDIUM Priority = "MEDIUM"
	HIGH Priority = "HIGH"
	CRITICAL Priority = "CRITICAL"
)
