/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type Error struct {

	Code string `json:"code"`

	Message string `json:"message"`

	Details []ErrorDetailsInner `json:"details,omitempty"`
}
