/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"time"
)

type MoveEquipmentRequest struct {

	// Target location ID
	LocationId string `json:"locationId"`

	// Timestamp of the move (defaults to now)
	MovedAt time.Time `json:"movedAt,omitempty"`

	Note string `json:"note,omitempty"`
}
