/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type EquipmentPage struct {

	Content []Equipment `json:"content,omitempty"`

	TotalElements int32 `json:"totalElements,omitempty"`

	TotalPages int32 `json:"totalPages,omitempty"`

	Page int32 `json:"page,omitempty"`

	PageSize int32 `json:"pageSize,omitempty"`
}
