/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type TransitionServiceRequestStatusRequest struct {

	Status ServiceRequestStatus `json:"status"`

	// Required when transitioning to ASSIGNED
	AssignedTo string `json:"assignedTo,omitempty"`

	// Required when transitioning to CLOSED
	ResolutionNote string `json:"resolutionNote,omitempty"`
}
