/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type LocationBase struct {

	Building string `json:"building"`

	Floor string `json:"floor"`

	Department string `json:"department"`

	Room string `json:"room"`

	Description string `json:"description,omitempty"`
}
