/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

type EquipmentUpdate struct {

	Name string `json:"name"`

	Type string `json:"type"`

	// Unique inventory/asset number
	InventoryNumber string `json:"inventoryNumber"`

	SerialNumber string `json:"serialNumber,omitempty"`

	Manufacturer string `json:"manufacturer,omitempty"`

	Model string `json:"model,omitempty"`

	PurchaseDate string `json:"purchaseDate,omitempty"`

	WarrantyExpiry string `json:"warrantyExpiry,omitempty"`

	// Expected operational lifespan in years
	LifespanYears int32 `json:"lifespanYears,omitempty"`

	// Current location ID
	LocationId string `json:"locationId"`

	Notes string `json:"notes,omitempty"`

	Status EquipmentStatus `json:"status,omitempty"`
}
