/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi
// EquipmentStatus : - `ACTIVE` – in normal use - `IN_SERVICE` – undergoing maintenance/repair - `DECOMMISSIONED` – retired from service 
type EquipmentStatus string

// List of EquipmentStatus
const (
	ACTIVE EquipmentStatus = "ACTIVE"
	IN_SERVICE EquipmentStatus = "IN_SERVICE"
	DECOMMISSIONED EquipmentStatus = "DECOMMISSIONED"
)
