/*
 * Hospital Equipment & Service Management API
 *
 * API for managing hospital equipment inventory, service requests, and location tracking.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package inventoryapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the EquipmentAPI part of the API
	EquipmentAPI EquipmentAPI
	// Routes for the LocationsAPI part of the API
	LocationsAPI LocationsAPI
	// Routes for the ServiceRequestsAPI part of the API
	ServiceRequestsAPI ServiceRequestsAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"CreateEquipment",
			http.MethodPost,
			"/v1/equipment",
			handleFunctions.EquipmentAPI.CreateEquipment,
		},
		{
			"DecommissionEquipment",
			http.MethodDelete,
			"/v1/equipment/:equipmentId",
			handleFunctions.EquipmentAPI.DecommissionEquipment,
		},
		{
			"GetEquipment",
			http.MethodGet,
			"/v1/equipment/:equipmentId",
			handleFunctions.EquipmentAPI.GetEquipment,
		},
		{
			"ListEquipment",
			http.MethodGet,
			"/v1/equipment",
			handleFunctions.EquipmentAPI.ListEquipment,
		},
		{
			"ListEquipmentServiceRequests",
			http.MethodGet,
			"/v1/equipment/:equipmentId/service-requests",
			handleFunctions.EquipmentAPI.ListEquipmentServiceRequests,
		},
		{
			"MoveEquipment",
			http.MethodPatch,
			"/v1/equipment/:equipmentId/location",
			handleFunctions.EquipmentAPI.MoveEquipment,
		},
		{
			"UpdateEquipment",
			http.MethodPut,
			"/v1/equipment/:equipmentId",
			handleFunctions.EquipmentAPI.UpdateEquipment,
		},
		{
			"CreateLocation",
			http.MethodPost,
			"/v1/locations",
			handleFunctions.LocationsAPI.CreateLocation,
		},
		{
			"DeleteLocation",
			http.MethodDelete,
			"/v1/locations/:locationId",
			handleFunctions.LocationsAPI.DeleteLocation,
		},
		{
			"GetLocation",
			http.MethodGet,
			"/v1/locations/:locationId",
			handleFunctions.LocationsAPI.GetLocation,
		},
		{
			"ListEquipmentAtLocation",
			http.MethodGet,
			"/v1/locations/:locationId/equipment",
			handleFunctions.LocationsAPI.ListEquipmentAtLocation,
		},
		{
			"ListLocations",
			http.MethodGet,
			"/v1/locations",
			handleFunctions.LocationsAPI.ListLocations,
		},
		{
			"UpdateLocation",
			http.MethodPut,
			"/v1/locations/:locationId",
			handleFunctions.LocationsAPI.UpdateLocation,
		},
		{
			"CreateServiceRequest",
			http.MethodPost,
			"/v1/service-requests",
			handleFunctions.ServiceRequestsAPI.CreateServiceRequest,
		},
		{
			"DeleteServiceRequest",
			http.MethodDelete,
			"/v1/service-requests/:requestId",
			handleFunctions.ServiceRequestsAPI.DeleteServiceRequest,
		},
		{
			"GetServiceRequest",
			http.MethodGet,
			"/v1/service-requests/:requestId",
			handleFunctions.ServiceRequestsAPI.GetServiceRequest,
		},
		{
			"ListServiceRequests",
			http.MethodGet,
			"/v1/service-requests",
			handleFunctions.ServiceRequestsAPI.ListServiceRequests,
		},
		{
			"TransitionServiceRequestStatus",
			http.MethodPatch,
			"/v1/service-requests/:requestId/status",
			handleFunctions.ServiceRequestsAPI.TransitionServiceRequestStatus,
		},
		{
			"UpdateServiceRequest",
			http.MethodPut,
			"/v1/service-requests/:requestId",
			handleFunctions.ServiceRequestsAPI.UpdateServiceRequest,
		},
	}
}
